os:
  - linux
sudo: false
before_install:
  - export FLUTTER_HOME="${HOME}/flutter"
  - export DART_HOME="$FLUTTER_HOME/bin/cache/dart-sdk/"
  - export PATH="$FLUTTER_HOME/bin:$DART_HOME/bin:$PATH"
install:
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1 $FLUTTER_HOME
  - flutter doctor
  - flutter packages get
  - cd business/ && flutter packages get && cd ..
  - cd client/ && flutter packages get && cd ..
script:
  # running there are some built_value classes that exist in both of these modules
  - cd business/ && flutter packages pub run build_runner build && cd ..
  - cd client/ && flutter packages pub run build_runner build && cd ..
  - flutter analyze --dartdocs
  - dartfmt -n . --set-exit-if-changed
  - flutter test --coverage --coverage-path=lcov.info .
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
